src/main/java/com/fkb/model/item/MediaObject.java
/* Copyright (c) 2009 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.fkb.model.item;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.PrimaryKey;

import com.google.appengine.api.blobstore.BlobKey;
import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;

@PersistenceCapable(identityType = IdentityType.APPLICATION, detachable="true")
public class MediaObject {
	@PrimaryKey
	@Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
	private Key key;

	@Persistent
	private String username;

	@Persistent
	private String title;

	@Persistent
	private String description;

	@Persistent
	private int zipcode;

	@Persistent
	private String type;

	@Persistent
	private Date creation;

	@Persistent
	private Date modification;

	// optional

	@Persistent
	private BlobKey blob;

	@Persistent
	private String contentType;

	@Persistent
	private String filename;

	@Persistent
	private long size;

	private static final List<String> IMAGE_TYPES = Arrays.asList("image/png",
			"image/jpeg", "image/tiff", "image/gif", "image/bmp");

	public MediaObject(String username, BlobKey blob, String contentType,
			String filename, long size, String title, String description,
			int zipcode, String type, Date creationTime, Date modificationTime) {

		this.username = username;
		this.blob = blob;
		this.contentType = contentType;
		this.filename = filename;
		this.size = size;
		this.title = title;
		this.description = description;
		this.zipcode = zipcode;
		this.type = type;
		this.creation = creationTime;
		this.modification = modificationTime;

	}

	public MediaObject(String username, String title, String description,
			int zipcode, String type, Date creationTime, Date modificationTime) {
		this(username, null, null, null, 0, title, description, zipcode, type,
				creationTime, modificationTime);
	}

	public Key getKey() {
		return key;
	}
	
	public String getWebSafeKey() {
		return KeyFactory.keyToString(this.key);
	}

	public String getDescription() {
		return description;
	}

	public String getTitle() {
		return title;
	}

	public String getFilename() {
		return filename;
	}

	public long getSize() {
		return size;
	}

	public String getUsername() {
		return username;
	}

	public int getZipcode() {
		return zipcode;
	}

	public String getType() {
		return type;
	}

	public Date getCreation() {
		return creation;
	}

	public Date getModification() {
		return modification;
	}

	public BlobKey getBlob() {
		return blob;
	}

	public static List<String> getImageTypes() {
		return IMAGE_TYPES;
	}

	public String getContentType() {
		if (contentType == null) {
			return "text/plain";
		}
		return contentType;
	}

	public boolean isImage() {
		return IMAGE_TYPES.contains(getContentType());
	}
}

src/main/java/com/fkb/controller/ErrorController.java
package com.fkb.controller;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * The error controller.
 */
@Controller
public class ErrorController {

    /**
     * Error code.
     *
     * @param errorCode the error code
     * @param modelMap the model map
     * @return the model and view
     */
    @RequestMapping(value = "/error/{errorCode}", method = RequestMethod.GET)
    public final String errorCode(
        @PathVariable("errorCode") final String errorCode,
        final ModelMap modelMap) {
        modelMap.put("statusCode", errorCode);
        return "error";
    }

}

src/main/java/com/fkb/controller/LoginController.java
package com.fkb.controller;

import java.util.HashMap;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.fkb.model.auth.UserAccount;
import com.fkb.service.auth.EnhancedUserDetailsService;

/**
 * The login controller.
 */
@Controller
public class LoginController {

    /**
     * The user details service.
     */
    private EnhancedUserDetailsService userDetailsService;

    /**
     * Gets the user details service.
     *
     * @return the user details service
     */
    public final EnhancedUserDetailsService getUserDetailsService() {
        return userDetailsService;
    }

    /**
     * Sets the user details service.
     *
     * @param userDetailsService the user details service
     */
    @Autowired
    public final void setUserDetailsService(
        final EnhancedUserDetailsService userDetailsService) {
        this.userDetailsService = userDetailsService;
    }

    /**
     * Adds an identifier to the model map to indicate there was an error
     * logging in.
     *
     * @param modelMap the model map
     * @return the view name
     */
    @RequestMapping(value = "/login/error", method = RequestMethod.GET)
    public final String error(final ModelMap modelMap) {
        modelMap.put("error", true);
        return "login";
    }

    /**
     * Determines if an account with the given username exists or not.
     *
     * @param request the request
     * @return the response
     */
    @RequestMapping(value = "/login/validate", method = RequestMethod.POST)
    @ResponseBody
    public final Map<String, Boolean> validate(
        @RequestBody final Map<String, String> request) {
        final Map<String, Boolean> response = new HashMap<String, Boolean>();
        final UserAccount user =
            userDetailsService.getUser(request.get("username"));

        response.put("found", user != null);

        return response;
    }

}

src/main/webapp/WEB-INF/view/activate.jsp
<%@ page isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
    <head>
        <title><spring:message code="activate.title" /></title>
    </head>
    <body>
        <c:choose>
            <c:when test="${not empty error}">
                <h2><spring:message code="activate.error" /></h2>
            </c:when>
            <c:otherwise>
                <h2><spring:message code="activate.header" /></h2>
            </c:otherwise>
        </c:choose>
        <p><spring:message code="global.login" htmlEscape="false" /></p>
    </body>
</html>

src/main/webapp/WEB-INF/view/admin.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
    <head>
        <title><spring:message code="admin.title" /></title>
    </head>
    <body>
		<h3><spring:message code="admin.header" /></h3>
		<ul>
        <li><spring:message code="admin.flush" htmlEscape="false" /></li>
    </ul>
	</body>
</html>

src/main/webapp/WEB-INF/view/create.jsp
<%@ page isELIgnored="false" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<html>
    <head>
        <title><spring:message code="create.title" /></title>
    </head>
    <body>
		    <form:form modelAttribute="register" action="/register/create" method="post">
            <fieldset>      
                <legend><spring:message code="create.legend" /></legend>
                <p> 
                    <form:label for="username" path="username" cssErrorClass="error"><spring:message code="create.label.username" /></form:label>
                    <form:input path="username" />
                    <form:errors path="username" cssClass="error" />
                </p>
                <p>
                    <form:label for="email" path="email" cssErrorClass="error"><spring:message code="create.label.email" /></form:label>
                    <form:input path="email" />
                    <form:errors path="email" cssClass="error" />
                </p>
                <p> 
                    <form:label for="password" path="password" cssErrorClass="error"><spring:message code="create.label.password" /></form:label>
                    <form:password path="password" />
                    <form:errors path="password" cssClass="error" />
                </p>
                <p>
                    <input name="reset" type="reset" value="<spring:message code="global.reset" />" /> 
                    <input name="submit" type="submit" value="<spring:message code="global.submit" />" />
                </p>
            </fieldset>
        </form:form>
    </body>
</html>

src/main/webapp/WEB-INF/view/createSuccess.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
    <head>
        <title><spring:message code="createSuccess.title" /></title>
    </head>
    <body>
        <h2><spring:message code="createSuccess.header" /></h2>
        <p><spring:message code="createSuccess.info" /></p>
    </body>
</html>

src/main/webapp/WEB-INF/view/error.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
    <head>
        <title><spring:message code="error.title" /></title>
    </head>
    <body>
        <h2><spring:message code="error.header" /></h2>
        <c:if test="${not empty exception}">
            <h3><spring:message code="error.exception" /> <c:out value="${exception}" /></h3>
        </c:if>
        <c:if test="${not empty statusCode}">
            <h3><spring:message code="error.status" /> <c:out value="${statusCode}" /></h3>
        </c:if>
    </body>
</html>

src/main/webapp/WEB-INF/view/index.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<html>
    <head>
        <title><spring:message code="index.title" /></title>
    </head>
    <body>
        <sec:authorize access="isAnonymous()">
            <p><spring:message code="global.login" htmlEscape="false" /></p>
        </sec:authorize>
        <sec:authorize access="isAuthenticated()">
            <p><spring:message code="global.logout" htmlEscape="false" /></p>
        </sec:authorize>
    </body>
</html>

src/main/webapp/WEB-INF/view/listItems.jsp
<%@page import="com.google.appengine.api.datastore.KeyFactory"%>
<%@page import="com.google.appengine.api.datastore.Key"%>
<%@ page isELIgnored="false"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="sec"
	uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%
	String principleUsername = null;
%>

<html>
<head>
</head>
<body>
	<sec:authorize access="isAnonymous()">
		<p>
			<spring:message code="global.login" htmlEscape="false" />
		</p>
	</sec:authorize>
	<sec:authorize access="isAuthenticated()">
		<p>
			<spring:message code="global.logout" htmlEscape="false" />
		</p>
		<c:set var="principleUsername">
			<sec:authentication property="principal.username" />
		</c:set>
	</sec:authorize>

	<c:forEach var="mediaObj" items="${itemList}">
   Posted By: ${mediaObj.username}<br>
   Title: ${mediaObj.title}<br>
   Description: ${mediaObj.description}<br>
   Zipcode: ${mediaObj.zipcode}<br>
   Last Modified: ${mediaObj.modification}<br>
   Created At: ${mediaObj.creation}<br>
		<c:if test="${mediaObj.blob != null}">
			<iframe width="300" height="250" seamless="seamless" scrolling="no"
				src="/item/image/${mediaObj.blob.keyString}"></iframe>
		</c:if>
		<c:if test="${editable}">
			<c:if test="${principleUsername == mediaObj.username}">
				<a href="/item/delete/${mediaObj.webSafeKey}">DELETE</a>
				<br>
			</c:if>
		</c:if>
		<hr>
	</c:forEach>
</body>
</html>

src/main/webapp/WEB-INF/view/login.jsp
<%@ page isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<html>
    <head>
        <title><spring:message code="login.title" /></title>
    </head>
    <body>
        <sec:authorize access="isAnonymous()">
		        <h3><spring:message code="login.header" /></h3>
		
		        <c:if test="${not empty error}">
      			    <p class="error"><spring:message code="login.error" /></p>
		        </c:if>
		
	    	    <p id="userWarning" class="error" style="display:none"><spring:message code="login.nouser" /></p>
		
    		    <form action="/login/submit" method="post">
		    	      <table>
    		    	      <tr><td><spring:message code="login.label.username" /></td><td><input type="text" name="username" value="<c:if test="${not empty error}"><c:out value="${SPRING_SECURITY_LAST_USERNAME}" escapeXml="false" /></c:if>"/></td></tr>
    			          <tr><td><spring:message code="login.label.password" /></td><td><input type="password" name="password" /></td></tr>
        			      <tr><td><spring:message code="login.label.remember" /></td><td><input type="checkbox" name="remember_me" /></td></tr>
        			      <tr><td><input name="reset" type="reset" value="<spring:message code="global.reset" />" /></td><td><input name="submit" type="submit" value="<spring:message code="global.submit" />" /></td></tr>
      			    </table>
		        </form>
		
		        <p><spring:message code="login.create" htmlEscape="false" /></p>
		    </sec:authorize>

        <sec:authorize access="isAuthenticated()">
            <p><spring:message code="global.logout" htmlEscape="false" /></p>
        </sec:authorize>

		    <script type="text/javascript">
            $(document).ready(function () {
                $("input[name='username']").blur(function () {
                    var values = {};
                    values['username'] = this.value;
                    
                    sendJson(
                        values,
                        '/login/validate',
                        function(result) { 
                            if (result.found) {
                                $('#userWarning').hide();
                            } else {
                                $('#userWarning').show();
                            }
                        }
                    );
                });
            });
        </script>
	  </body>
</html>

src/main/webapp/WEB-INF/view/postItem.jsp
<%@ page isELIgnored="false"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="sec"
	uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<html>
<head>
<title><spring:message code="post_item.title" /></title>
</head>
<body>
	<sec:authorize access="isAnonymous()">
		<p>
			<spring:message code="global.login" htmlEscape="false" />
		</p>
	</sec:authorize>
	<sec:authorize access="isAuthenticated()">
		<p>
			<spring:message code="global.logout" htmlEscape="false" />
		</p>
	</sec:authorize>


	<form:form modelAttribute="item" action="${uploadUrl}" method="post"
		enctype="multipart/form-data">
		<fieldset>
			<p>
				<form:select path="type">
					<form:option value="OFFER" label="Offer" />
					<form:option value="WANTED" label="Wanted" />
				</form:select>
			</p>
			<p>
				<form:label for="title" path="title" cssErrorClass="error">
					<spring:message code="post_item.label.title" />
				</form:label>
				<form:input path="title" />
				<form:errors path="title" cssClass="error" />
			</p>
			<p>
				<form:label for="description" path="description"
					cssErrorClass="error">
					<spring:message code="post_item.label.description" />
				</form:label>
				<form:textarea path="description" />
				<form:errors path="description" cssClass="error" />
			</p>
			<p>
				<form:label for="zipcode" path="zipcode" cssErrorClass="error">
					<spring:message code="post_item.label.zipcode" />
				</form:label>
				<form:input path="zipcode" />
				<form:errors path="zipcode" cssClass="error" />
			</p>

			<p>
				<form:label for="fileData" path="fileData" cssErrorClass="error">
					<spring:message code="post_item.label.fileData" />
				</form:label>
				<form:input path="fileData" type="file" />
			</p>
			<p>
				<input name="reset" type="reset"
					value="<spring:message code="global.reset" />" /> <input
					name="submit" type="submit"
					value="<spring:message code="global.submit" />" />
			</p>
		</fieldset>
	</form:form>
</body>
</html>